blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name = 'all_blogs'),
#    path('', views.tree, name = 'blog/'),
#    path('tree/', views.tree, name = 'blog'),
#    path('<int:id>/', ArticleDetailView.as_view(), name = 'blog_page'),
    path('<int:blog_id>/', views.blog_page, name = 'blog_page'),
]

portfolioproject/urls.py
from django.contrib import admin
from django.urls import path, include
from portfolio import views
from django.conf import settings
#from blog import views as blogviews
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name = 'home'),
    path('blog/', include('blog.urls')),
#    path('tree/', blogviews.tree),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

#urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Posts(models.Model):
    tittle = models.CharField(max_length = 200)
    descriptions = models.TextField()
    date = models.DateTimeField()

    def __str__(self):
        return self.tittle



        

portfolio/models.py
from django.db import models
#from django.db import models.Model
# Create your models here.

class Project(models.Model):
    tittle = models.CharField(max_length = 100)
    discriptions = models.CharField(max_length =250)
    image = models.ImageField(upload_to ='portfolioapp/images/')
    url = models.URLField(blank = True)

    def __str__(self):
        return self.tittle

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Posts


# Create your views here.
def blog(request):
    posts = Posts.objects.all()
    return render(request, 'blog.html', {'posts':posts}, )


def all_blogs(request):
    posts = Posts.objects.all()
    return render(request, 'blog/all_blogs.html', {'posts':posts})

def blog_page(request, blog_id):
#    posts = Posts.objects.filter(pk=blog_id)
    post = get_object_or_404(Posts,pk=blog_id)
# {'posts':posts}, {'post':post}
    return render(request, 'blog/blog_page.html', {'post':post}, {'id':blog_id} )




'''
7*8
10*8
1-этаж
общепит на вынос
Партенит
потолок - веранда
'''

portfolio/views.py
from django.shortcuts import render
from .models import Project


# Create your views here.
def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio\home.html', {'projects' : projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio\base.html' %}
{% block content %}


<h3>
  <p style="text-align: center;">
  Страница блога содержит {{ posts.count }} поста
  </p>
</h3>
<br>
{% for post in posts %}

<br>
    <a href = "{{ post.id }}"><h3>
      <p style="text-align: center;">
        {{ post.tittle }}
        </p>
      </h3></a>
  </p>
<p style="text-align: center;">{{ post.date }}</p>
<p style="text-align: center;">{{ post.descriptions }}</p>

{% endfor %}

{% endblock %}

blog/templates/blog/blog.html
<a href = "{% url 'home' %}"><h1>Главная</h1></a>
<a href = "{% url 'blog/' %}"><h1>Блог</h1></a>
<br>
Text from dictionary
{{ posts }}
{{ test }}
{{ blogs }}
{{ projects }}

{% for post in posts %}
{{ post.tittle }}
{% endfor %}

blog/templates/blog/blog_page.html
{{ post.tittle }}
{{ post.date }}
{{ post.descriptions }}

portfolio/templates/portfolio/base.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <!---->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!---->

  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href=" {% url 'home' %}">Мое портфолио</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <a class="navbar-brand" href="{% url 'blog:all_blogs' %}">Блог</a>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% static 'portfolio\stepik-certificate-67-de4220e(1).pdf' %}">Cертификат</a>
            </li>


          </ul>
        </div>
      </div>
    </nav>

{% block content %}
{% endblock %}

  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% block content %}


{% load static %}

<h1>
<p style="text-align: center;">
  Это мое резюме
</p>
</h1>
<br>
<p style="text-align: center;">
<img src = "{% static 'MG8149.jpg' %}" height="550 px" weight = "550 px" align = "center" title="Мое фото" class="rounded mx-auto d-block">
</p>
<a href = "{% static 'portfolio\stepik-certificate-67-de4220e(1).pdf' %}">
  <p style="text-align: center;">
    Ссылка на сертификат
    </p>
  </a>
<br>

<div id="parent" class="row">
{% for project in projects %}

    <div class="col-4">
        <a href = "{% url 'home' %}"> <h3 class="text-center"> {{ project.tittle }} </h3></a>
        <br>
        <h5 class="text-center">{{ project.discriptions }}</h5>
        <br>
        <img src = "{{ project.image.url }} " wigth='100 px' height='100 px' class="rounded mx-auto d-block">
        <br>

        {% if project.url %}
        <a href="{{ project.url }}"> <p class="text-center"> {{ project.url }} </p></a>
        <a href = "{{ project.url }}"> <p class="text-center">Ссылка указанная в Карточке </p></a>
        {% endif %}
    </div>

{% endfor %}
</div>

{% endblock %}